language: python

os:
- linux

dist: trusty
env:
  - ARCH=x86_64

sudo: required

python:
  - "3.5"

branches:
  only:
    - development_qa

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script:  # need to add jumpscale part
  - 
      
script: 
  - nimble zos
  - sudo python3 ./qa/zos_testcase.py

