language: python

os: linux
dist: trusty
env: ARCH=x86_64
sudo: true
python: 3.5
branches:
  only:
    - development_qa

before_install:
# prepare the machine for jumpscale installation 
  - sudo apt-get update
  - sudo apt-get install -y python3.5 python3.5-dev
  - sudo rm -f /usr/bin/python
  - sudo rm -f /usr/bin/python3
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3
  - sudo apt-get -y install python3-gdbm 

install: 
  - sudo ./.travis_ci/prepare.sh

before_script: 
  # download zos binary and working with it 
  - wget https://github.com/threefoldtech/zos/releases/download/0.1.6/zos_linux
  - sudo cp zos_linux /usr/bin/zos
  - sudo chmod +x /usr/bin/zos
  # install zerotier on the machine
  - curl -s https://install.zerotier.com/ | sudo bash
  - sudo service zerotier-one start
  - sudo zerotier-cli join c7c8172af1f387a6
  
script: sudo python3 ./qa/zos_testcase_node.py

