language: python

os: linux
dist: trusty
env: ARCH=x86_64
sudo: true
python: 3.5

branches:
  only:
    - development_qa

before_install:
# prepare the machine for jumpscale installation 
  - sudo apt-get update
  - sudo apt-get install -y python3.5 python3.5-dev
  - sudo rm -f /usr/bin/python
  - sudo rm -f /usr/bin/python3
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3
  - sudo apt-get -y install python3.5-gdbm 

install: 
  - sudo ./.travis_ci/prepare.sh

before_script: 
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble zos
      
script: sudo python3 ./qa/zos_testcase.py

