language: python

os:
- linux

dist: trusty
env:
  - ARCH=x86_64

sudo: required

python:
  - "3.5"

branches:
  only:
    - development_qa

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script: 
  - | 
      export JUMPSCALEBRANCH=${JUMPSCALEBRANCH:-development}
      export JSFULL=1
      curl https://raw.githubusercontent.com/threefoldtech/jumpscale_core/$JUMPSCALEBRANCH/install.sh?$RANDOM > /tmp/install_jumpscale.sh;sudo -HE bash -c 'bash /tmp/install_jumpscale.sh'
      
script:
  - nimble zos
  - sudo python3 ./qa/zos_testcase.py

